apiVersion: v1
baseDomain: <domain>
compute:
- hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      type: m5a.xlarge
  replicas: 1
metadata:
  creationTimestamp: null
  name: <cluster_name>
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: ap-southeast-1
publish: External
pullSecret: <pull_secret>
sshKey: |
<~/.ssh/id_rsa.pub>
